FROM node:20-alpine as builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
RUN npm install
RUN npm install @prisma/client
RUN npx prisma generate

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]