FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/
COPY server/worker/ ./app/server/worker/

RUN apk add --no-cache openssl
RUN npm install
RUN npm ci
RUN npm i helmet
RUN npm cache clean --force

COPY . .

RUN npx prisma generate

CMD ["node", "server/worker.js"]