services:
  - type: web
    name: imaryza-api
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: imaryza-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://imaryza.onrender.com
      - key: REDIS_URL
        fromService:
          name: imaryza-redis
          type: redis
          property: connectionString
    autoDeploy: true

  - type: worker
    name: imaryza-worker
    env: node
    region: oregon
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: node server/worker/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: imaryza-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: imaryza-redis
          type: redis
          property: connectionString

  - type: web
    name: imaryza-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://imaryza-api.onrender.com/api

  - type: redis
    name: imaryza-redis
    ipAllowList: []
    plan: starter

databases:
  - name: imaryza-db
    databaseName: imaryza
    plan: free
    ipAllowList: []
